server:
  port: 9091
  session:
    timeout: 1800

#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/foodmarket?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
#spring.datasource.username=root
#spring.datasource.password=root

logging:
  level:
    org.springframework.web: DEBUG

spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.135.132:3306/foodmarket?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: csgcsg2017
#  data:
#    rest:
#      base-path: /api
      
